### PR TITLE
Add BTX support

### PR DESCRIPTION
**Pull request by dalijolijo**

### CODE REVIEW

**Comment by dalijolijo** [comment]
@chill117 @karliatto What is missing to merge?

**Comment by chill117** [comment]
Hello, we have been researching Bitcore (BTX). Part of the idea behind this project (CryptoTerminal) is to help guide newbies (both merchants and their customers) through the learning process. So we want to be sure that any new payment methods that are added to the app are legitimate and serve a real use-case.

Perhaps you can help us to understand the use-case and purpose for the Bitcore project by providing some links to technical details. I've so far not been able to find them on my own.

Thank you for your understanding and patience.

**Comment by dalijolijo** [comment]
Hello.
Please have a look on these links:
Bitcore Website : https://bitcore.cc
Bitcore Github Repo : https://github.com/LIMXTEC/BitCore
Awesome Bitcore link list : https://github.com/LIMXTEC/awesome-bitcore-btx

If you have any questions let me know.

**Comment by chill117** [comment]
This project already supports Bitcoin, Litecoin, and Lightning Network. Most of the main features of Bitcore (BTX) seem to already be provided by one (or some combination) of these payment methods. So I don't think it makes sense for us to add support for Bitcore at this time.

Thank you for taking the time to create these pull-requests. We wish you well and good luck with the Bitcore project.

**Comment by dalijolijo** [comment]
Hello.
Bitcore (BTX) is legitimate and serve a real use-case with very high TPS and one of the lowest tx fees.

image
image

In the following article you can find real use case examples: http://www.cryptoinnout.com/news-20181107-scalability-problem-and-bitcore-btx-491.html

I hope I have convinced you with technical facts, that it is worthwhile to support BTX with CryptoTerminal.

BTW: I contributed the german translation to this great project: https://github.com/samotari/crypto-terminal/pull/303

**Comment by chill117** [comment]
Hello @dalijolijo 

We've created a [contribution guideline](https://github.com/samotari/crypto-terminal/blob/master/CONTRIBUTING.md) that should clearly articulate our stance on adding new payment methods.

In the case of bitcore (BTX), there are two main reasons that we don't want to support it at this time:
* We feel that it doesn't yet differentiate itself enough from the payment methods already supported by this app (bitcoin, litecoin, monero, lightning network).
* Bitcore doesn't appear to have a sufficient user base to warrant the additional support costs for us.

We appreciate and thank you for the effort that you put into your pull-requests.

**Pull request closed without merging**
